### ISSUE TITLE
Get the contact statistics date wise.

### ISSUE THREAD

**Issue by jot11** [mailjet/mailjet-apiv3-dotnet#10]
I am using Asp.net wrapper to get the details of sent emails(contact wise),
Is there any option or method exist so that I can get the contact statistics date wise , or of today , or month wise , or  yearly !

**Comment by latanasov** [comment]
Hi @jot11 ,
Your use-case can probably be implemented through the [/messagesentstatistics](https://dev.mailjet.com/email-api/v3/messagesentstatistics/) resource with filters on  `FromTS ` - `ToTS `and `Contact`. 

If you have further API related questions please raise a ticket through Mailjet Support.

**Comment by jot11** [comment]
I have question ! as I am very new to the MailJetApi integration 
Do I get any example where I can see use of the filter in Asp.net wrapper

**Comment by latanasov** [comment]
Hi @jot11  you can find examples with filters and our wrapper in the guide [here ](https://dev.mailjet.com/guides/?csharp#resource-filters) .
