### ISSUE TITLE
Getting Error "Email already exists" When its not in the contact list

### ISSUE THREAD

**Issue by anandtpatel** [mailjet/mailjet-apiv3-dotnet#103]
This email does not exists in the database and I am getting this error. Infact getting same error for most of the contact. Whats the issue?

```
[  
   {    "ErrorInfo": "",
        "ErrorMessage": "MJ18 A Contact resource with value "dougxsarah111@yahoo.com" for Email already exists.",
       "StatusCode": 400
   }
]
```

**Comment by dmytrosvystun88** [comment]
Please provide more details on what you are trying to accomplish, maybe send some sample code. Also please specify what version of mailjet wrapper you are using.

**Comment by dmytrosvystun88** [comment]
Here you can find examples on how to perform basic operations on contacts (create, get, delete):
https://github.com/mailjet/mailjet-apiv3-dotnet/blob/master/Mailjet.Tests/Integration/ContactsIntegrationTests.cs

**Comment by dmytrosvystun88** [comment]
This is closed due to inactivity. Feel free to re-open in case of need.
