### ISSUE TITLE
Numeric properties in variable objects not serialising correctly when there is a zero value.

### ISSUE THREAD

**Issue by purplepiranha** [mailjet/mailjet-apiv3-dotnet#105]
I have a template with the following code:

```
<p style="color: #AC4FC6; font-size: 1.1em; font-weight: bold; margin: 5px 10px;">Product(s) in your cart</p>
<table cellpadding="5" cellspacing="0" border="0" style="width: 100%;">
   {% for Item in var:Items %}
   <tr>
      <td valign="middle" width="56" align="right"><img src="{{ Item.ImageUrl }}" width="56" /></td>
      <td valign="middle">
         <p style="font-size: 1.1em; font-weight: bold; color: #000; margin: 0;">{{ Item.Name }}</p>
         <p style="font-size: 1em; font-weight: bold; color: #000; margin: 0;">&pound;{{ Item.Price }}</p>
      </td>
   </tr>
   {% endfor %}
</table>
```
I send the following JSON to the API endpoint using Postman:

```
{
    "Messages":[
            {
                "From": {
                        "Email": "noreply@...",
                        "Name": "Test"
                },
                "To": [
                        {
                                "Email": "paul@...",
                                "Name": "Paul"
                        }
                ],
                "TemplateID": 1,
                "TemplateLanguage": true,
                "TemplateErrorReporting": {
                    "Email": "paul@...",
                    "Name": "Error Email"
                },
                "TemplateErrorDeliver": true,
                "Variables": {
                    "Items": [
                        { "Name": "Test Product", "Price": 1.99, "ImageUrl": "https://..." },
                        { "Name": "Test Product 2", "Price": 3, "ImageUrl": "https://..." },
                        { "Name": "Free Product", "Price": 0, "ImageUrl": "https://..." }
                    ]
                }
            }
    ]
}
```
I get the expected result of:
![image](https://user-images.githubusercontent.com/15064668/198004241-b686037c-34c0-4d34-9fd2-6e67e7ad8675.png)

However, sending via the C# client library using the following code:
```
public async Task SendTestEmail()
{
   var items = new List<Item>();
   items.Add(new Item() { Name = "Test Product", Price = 1.99m, ImageUrl = dummyImageUrl });
   items.Add(new Item() { Name = "Test Product 2", Price = 3m, ImageUrl = dummyImageUrl });
   items.Add(new Item() { Name = "Free Product", Price = 0m, ImageUrl = dummyImageUrl });

   var variables = new Dictionary<string, object>();
   variables.Add("Items", items);

   var email = new TransactionalEmailBuilder()
      .WithTemplateId(mailjetTemplateId)
      .WithTemplateLanguage(true)
      .WithTo(toContact)
      .WithVariables(variables)
      .WithTemplateErrorReporting(errorContact)
      .WithReplyTo(fromContact)
      .Build();

   await mailjetClient.SendTransactionalEmailAsync(email);
}

private class Item
{
   public string Name { get; set; }
   public decimal Price { get; set; }
   public string ImageUrl { get; set; }
}
```
The zero value is not pulled through for the third item:
![image](https://user-images.githubusercontent.com/15064668/198005215-26c7ecd5-7df8-428e-82ea-73bedd4b242b.png)

And more interestingly, the price property doesn't seem to exist at all on that item, meaning that I don't seem to have any way within the template markup to check. I've tried:

```
{% if Item.Price:true %}
&pound;{{ Item.Price }}
{% else %}
&pound;0
{% endif %}
```
And this just gives the following error:
```
A template language occurred when sending a message using Template 4281743: expression parsing error ## Unknown identifier: Item.Price:true ## near ## Item.Price:true ##
```
The example above used the decimal type, but the same problem is also found with double and int. I haven't tried any others but it would appear to be any numeric type.

**Comment by dmytrosvystun88** [comment]
Hi, 
yes `DefaultValueHandling = DefaultValueHandling.Ignore,` was done intentionally to keep request size smaller.

Another option can be overriding the default value with the DefaultValueAttribute:
`internal class Item
    {
        public string Name { get; set; }
        [DefaultValue(null)]
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
    }`

Basically it is doing the same workaround but without changing the type of a variable.

**Comment by purplepiranha** [comment]
Unfortunately, there is another issue here. .NET has come a long way in the last few years and unfortunately this repo doesn't seem to be actively maintained.

With the introduction of the new record types and also primary constructors on records and classes, which eliminate a lot of boilerplate code, make it sensible to use records for template variables.

I feel that I should be able to do this:

```
public record Rate(
    string Name, 
    int PreviousQuantity, 
    int Quantity
    );
```
But, if I have to use a workaround:
```
public record Rate(
    string Name, 
    [DefaultValue(null)] int PreviousQuantity, 
    [DefaultValue(null)] int Quantity
    );
```

This seems logical, but the default values don't have any effect. I assume that this is because the serializer works on the properties that are created by the compiler, rather than the constructor parameters.

So I have to use:
```
public record Rate(
    string Name, 
    int? PreviousQuantity, 
    int? Quantity
    );
```

Interestingly, when I use:
```
public record Rate(
    string Name, 
    int PreviousQuantity, 
    int Quantity
    );
```
If:
`PreviousQuantity = 0`
`Quantity = 1`
Then the template works but the PreviousQuantity is rendered as blank.
If:
`PreviousQuantity = 1`
`Quantity = 0`
There is an expression parsing error.
In the template they are both rendered the same way:
```
{% for Rate in Group.Rates %}
      <tr>
        <td align="left">{{Rate.Name}}</td>
        <td width="10">&nbsp;</td>
        <td align="right">{{Rate.PreviousQuantity}}</td>
        <td width="10">&nbsp;</td>
        <td align="right">{{Rate.Quantity}}</td>
      </tr>
{% endfor %}
```
So it just seems inconsistent.

I wonder if there would be a way to serialize the variables separately from the config params, so that variables would always have all fields included.
