### ISSUE TITLE
Retrieving Message ID 

### ISSUE THREAD

**Issue by MearTechnology** [mailjet/mailjet-apiv3-dotnet#106]
Hi, 

When sending an email, how do I retrieve the message ID? 

I can see property CustomID, but it doesn't seem to contain any value on it.

`var response = await client.SendTransactionalEmailAsync(EmailToSend);`

Am I doing something wrong? 

Regards,

**Comment by dmytrosvystun88** [comment]
Hi @MearTechnology,
CustomID can be set by client side for tracking purposes. The request should have a value assigned to CustomID field and only then it will be available in the response.

![image](https://user-images.githubusercontent.com/4784289/235454756-3fad62f7-e351-438c-9939-e36ef6c2176b.png)

The message ID assigned by mailjet can be retrieved from the response here:
![image](https://user-images.githubusercontent.com/4784289/235457884-c033addf-70e2-493a-9bfc-ee1f22997359.png)
