### ISSUE TITLE
Default JSON serializer settings serialize properties in pascal case

### ISSUE THREAD

**Issue by borisStanojevic** [mailjet/mailjet-apiv3-dotnet#107]
The default JSON serialization settings in MailjetClient use pascal case property name resolving (by default). Since JSON properties are in camel case by nature, maybe it would be good to add the _ContractResolver = new CamelCasePropertyNamesContractResolver()_ to the serializer settings, **or** even better, allow for the settings to be injected through the constructor.

**Comment by dmytrosvystun88** [comment]
Hi!
Yes, we could inject the setting and set the desired contract resolver to CamelCasePropertyNamesContractResolver. But it looks like it doesn't bring value into the product. Please let me know if I'm missing something.

Considering that official Mailjet [documentation](https://dev.mailjet.com/email/reference/send-emails/) uses pascal case everywhere this change can add a confusion.
