### ISSUE TITLE
Rename TemplateErrorDelivery property into TemplateErrorDeliver and fix the bug with WithTemplateErrorDeliver method

### ISSUE THREAD

**Issue by FVilevski** [mailjet/mailjet-apiv3-dotnet#108]
WithTemplateErrorDeliver(shouldProceedWithMessageDeliveryInCaseOfErrors: true) is not working!

TransactionalEmail class is having wrongly named property for deliver of email when templates has errors.
In short according to [docs ](https://dev.mailjet.com/email/reference/send-emails/#v3_1_post_send) the property named as
TemplateErrorDelivery should be renamed to TemplateErrorDeliver in order to fix this bug.

**Comment by dmytrosvystun88** [comment]
@FVilevski thank you for your input, TemplateErrorDelivery is renamed.
