### ISSUE TITLE
Does personalization work for email subject?

### ISSUE THREAD

**Issue by mikalai-sauchanka** [mailjet/mailjet-apiv3-dotnet#114]
So far I managed to successfully got custom variables replaced in email body, but no in subject. I pass in "to[{index}].Vars".

<img width="583" alt="Screenshot 2023-06-30 at 18 55 01" src="https://github.com/mailjet/mailjet-apiv3-dotnet/assets/3226612/c40dd0dc-246f-4b21-b17e-2219567e9607">

**Comment by dmytrosvystun88** [comment]
Hi, @mikalai-sauchanka, 
since you've mentioned "to[{index}].Vars" I assume that you are using V3 api to send the email.

Enable template language to be able to replace custom variables in the subject. This code works for me:

`MailjetRequest request = new MailjetRequest
            {
                Resource = Send.Resource,
            }
            .Property(Send.FromEmail, "dmytro.svystun@sinch.com")
            .Property(Send.FromName, "Mailjet Pilot")
            .Property(Send.Subject, "Hello, {{var:RecipientFirstName}}")
            .Property(Send.TextPart, "Hello, {{var:RecipientFirstName}}")
            .Property(Send.HtmlPart, "Hello, {{var:RecipientFirstName}}")
            .Property(Send.Vars, new JObject {
                {"RecipientFirstName", "John Doe"}
                })
            .Property(Send.Recipients, new JArray {
                new JObject {
                 {"Email", "dmytro.svystun@sinch.com"},
                 {"Name", "passenger 1"},
                 {"Vars", new JObject {
                  {"RecipientFirstName", "John Doe"}
                  }}
                 },
                new JObject {
                 {"Email", "dmytro.svystun@sinch.com"},
                 {"Name", "passenger 2"}
                 }
                })
            .Property(Send.MjTemplateLanguage, "True");

            MailjetResponse response = await client.PostAsync(request);`


Documentation: https://dev.mailjet.com/email/guides/send-api-V3/#use-template-language

**Comment by dmytrosvystun88** [comment]
Documentation: https://dev.mailjet.com/email/guides/send-api-V3/#use-template-language

**Comment by mikalai-sauchanka** [comment]
Hi, @dmytrosvystun88. Thank you for your response!

Apparently I was using wrong syntax - square brackets instead of curly.
