### ISSUE TITLE
Create a Campaign

### ISSUE THREAD

**Issue by buddhika85** [mailjet/mailjet-apiv3-dotnet#12]
I get below error when I try to create a Campaign using MailJet API for .NET. 

Root = {{
  "ErrorInfo": "",
  "ErrorMessage": "Invalid json input: expected \",\", but found \"\"\" at stream position 133 ...ctsList\":\"|ContactLis...",
  "StatusCode": 400
}}

Below is code the,

var client = new MailjetClient(MjApikeyPublic, MjApikeyPrivate)
                {
                    Version = ApiVersion.V3
                };
                MailjetRequest request = new MailjetRequest
                    {
                        Resource = Campaigndraft.Resource,
                    }
                    .Property(Campaigndraft.Locale, "en_US")
                    .Property(Campaigndraft.Sender, "Mailjet Dv1")
                    .Property(Campaigndraft.SenderEmail, "buddhika_jet@outlook.com")
                    .Property(Campaigndraft.Subject, "Greetings from Mailjet")
                    .Property(Campaigndraft.ContactsList, "10152")
                    .Property(Campaigndraft.Title, "Friday newsletter");
                response = await client.PostAsync(request);

Im having doubts in the Campaigndraft.ContactsList value that I passed. Considering the official mailjet documentation the parameter should be (Ref - https://dev.mailjet.com/guides/?csharp#prepare-a-campaign),

.Property(Campaigndraft.ContactsListID, "$ID_CONTACTSLIST")

But I cannot find Campaigndraft.ContactsListID in the mailjet API version 3 or version 3.1.

Any help will be much appreciated. Thanks in advance.

**Comment by todorDim** [comment]
Hey @buddhika85,

I'm sorry for the late answer. Indeed you are right, the property was not the right one. It is fixed with this pull request https://github.com/mailjet/mailjet-apiv3-dotnet/pull/25. 

Regards,
T.
