### ISSUE TITLE
Cannot set template variables

### ISSUE THREAD

**Issue by emiliavanderwerf** [mailjet/mailjet-apiv3-dotnet#13]
I am using the API in the following way in order to attempt to set the variable "name" within my email template:

```
        public static async Task<bool> SendEmailWithTemplate(String templateID, String recipient, JObject variables)
        {
            MailjetRequest request = new MailjetRequest
            {
                Resource = Send.Resource,
            }
            .Property(Send.FromEmail, ConfigurationManager.AppSettings["MailJetFromEmail"].ToString())
            .Property(Send.FromName, "Support Team")
            .Property(Send.Subject, "Welcome")
            .Property(Send.MjTemplateID, WELCOME_EMAIL_TEMPLATE_ID)
            .Property(Send.Vars, new JObject
            {
                { "name", "Testing a name"}
            })
            .Property(Send.Recipients, new JArray
            {
                new JObject
                {
                    { "Email", recipient }
                }
            });

            MailjetResponse response = await client.PostAsync(request);

            if (response.IsSuccessStatusCode)
            {
                // Log success
            }
            else
            {
                // Log error
            }
        }
```

In this case, `IsSuccessStatusCode` is `true`, but in the screenshot is what the variable `name` looks like - it was not replaced with "Testing a name" when it should have been. 

Thanks for your help!
![sf](https://user-images.githubusercontent.com/28126679/39309897-e2018c44-491d-11e8-9ae7-b4e8cb25c473.JPG)

**Comment by kmanchikov** [comment]
Hi Emilia, 

In order for {{var:name}} to be replaced by the variable declared in the Send API Call { "name", "Testing a name"} you would also need to use the "TemplateLanguage" property within your Send API Payload, which could be done as follows, {"TemplateLanguage", true} 

You could also have a quick look into one of our examples here Emilia, ( https://dev.mailjet.com/guides/?csharp#using-templating-language ) just as a reference, as it might help. 

Best, 

Krassimir
