### ISSUE TITLE
.GetErrorInfo(), .GetErrorMessage() returns null even though there is an error

### ISSUE THREAD

**Issue by rakewell** [mailjet/mailjet-apiv3-dotnet#23]
Hello,

the response from var resp = await this._mailClient.PostAsync(req); captures the error in the _content member but it is not returned .GetErrorInfo() and .GetErrorMessage() methods.

**Comment by Thoradin89** [comment]
Hello @rakewell ,

We'll take a closer look at the issue and get back to you.

Regards,
T.

**Comment by abambova** [comment]
Hi @rakewell ,

Could you please share with us what you are trying to achieve and the code snippet you are using. All further details will be appreciated. Thanks!

**Comment by abambova** [comment]
Hello @rakewell,

We would like to help you with solving this issue but we need some further details, could you please send us more details? A code snippet or the API calls, every further information will allow us to reproduce the issue. Thanks!

**Comment by Crysis-Gomez** [comment]
I have the same issue. I generate an error on purpose for testing.
`    MailjetResponse response = await _client.PostAsync(request);
     var t = response.GetErrorMessage();`

But GetErrorMessage() returns an empty string.
However the Non-Public member _content has the following error message

{{
  "Messages": [
    {
      "Status": "error",
      "Errors": [
        {
          "ErrorIdentifier": "Just an example ",
          "ErrorCode": "send-0008",
          "StatusCode": 403,
          "ErrorMessage": "\"test@gmail.com\" is not an authorized sender email address for your account.",
          "ErrorRelatedTo": [
            "From"
          ]
        }
      ]
    }
  ]
}}

**Comment by Rippletank** [comment]
For anyone who needs help with this, it is because the MailjetResponse object is only setup for handling API v3 errors.

I got around it without having to mess with the library by using the TryGetValue method of the MailjetResponse. This returns a JArray. I just needed to determine if the error was due to a bad email address so I used the following rough and ready code:

Response is documented at [https://dev.mailjet.com/email/reference/send-emails/#v3_1_post_send](url)


                if (response.TryGetValue("Messages", out JArray messages))
                {
                    foreach(var m in messages)
                    {
                        var Errors = (JArray)m["Errors"];
                        if (Errors.Any(e=>e["ErrorCode"].ToString().Contains("mj-0013")))
                        {
                            //Handle Email format error
                        }
                    }
                }
