### ISSUE TITLE
Unable to delete contact, returns 401

### ISSUE THREAD

**Issue by st1pps** [mailjet/mailjet-apiv3-dotnet#24]
Hi,
To comply with the GDPR we need to implement a function on our website that allows users to delete their personal data. While implementing this process, I noticed that the MailJet C# client (or is it the api itself?) does not allow to delete contacts, though they can at least be "soft-deleted" via the mailjet website. 
At the moment we have to manually delete users who want their data deleted. 

Or am I maybe just doing it wrong?
`var request = new MailjetRequest
{
	Resource = Contact.Resource,
	ResourceId = ResourceId.Alphanumeric("myemail@address")
};
var response = await _client.DeleteAsync(request);`
The result is always a 401 status code. All other things I do via the API work just fine, the client is set up correctly.

**Comment by kmanchikov** [comment]
Hey there, 

Currently the feature to anonymize contacts with API is currently on pre-prod and not widely available for public use. However if you do go through our Support channel [here](https://app.mailjet.com/support/ticket) they would be able to find an solution for you right away. 

Be sure to open the ticket as an API one by choosing the "I have a request about Mailjet API" option from the drop down menu.
