### ISSUE TITLE
Simplify creating and sending a transactional email

### ISSUE THREAD

**Issue by maxstralin** [mailjet/mailjet-apiv3-dotnet#29]
It would seem easy to have property names being misspelled and since they're just magic strings, no compiler warnings if the properties would change.

Would expect an easy helper method so instead of:
```
var client = new MailjetClient("KEY", "SECRET");

MailjetRequest request = new MailjetRequest
         {
            Resource = Send.Resource,
         }
            .Property(Send.Messages, new JArray {
                new JObject {
                 {"From", new JObject {
                  {"Email", "pilot@mailjet.com"},
                  {"Name", "Mailjet Pilot"}
                  }},
                 {"To", new JArray {
                  new JObject {
                   {"Email", "passenger1@mailjet.com"},
                   {"Name", "passenger 1"}
                   }
                  }},
                 {"Subject", "Your email flight plan!"},
                 {"TextPart", "Dear passenger 1, welcome to Mailjet! May the delivery force be with you!"},
                 {"HTMLPart", "<h3>Dear passenger 1, welcome to Mailjet!</h3><br />May the delivery force be with you!"}
                 }
                });
         MailjetResponse response = await client.PostAsync(request);
```
a developer could use
```
var client = new MailjetClient("KEY", "SECRET");
var response = await client.SendEmailAsync(new TransactionalEmail {
 From = new Sender("pilot@mailjet.com", "Mailjet Pilot"), 
 To = new Recipient("passenger1@mailjet.com", "passenger 1") //Also accepts IEnumerable<Recipient>,
 TextPart = "Dear passenger 1, welcome to Mailjet! May the delivery force be with you!",
 HtmlPart = "<h3>Dear passenger 1, welcome to Mailjet!</h3><br />May the delivery force be with you!",
 Subject = "Your email flight plan"
}
```
which would simply wrap the current procedure but enable for easier update and use.

I'd be happy to create a pull request if it'd be of interest.

**Comment by Thoradin89** [comment]
Hello @maxstralin,

Indeed your suggestion makes more sense. I'll review it internally with the development team and check if we can implement it in the next version of the wrapper.

Regards,
T.

**Comment by Emths** [comment]
@maxstralin and @Thoradin89 : Exactly what I did first! If I can add a suggestion : it should be wonderfull to add a "CustomHeader" class that you can pass as an optional parameter...
;-)

**Comment by goacoustic** [comment]
Hi, @maxstralin, thanks for raising this question!

I've added a possibility to use strongly typed models for sending transactional emails, as this is one of the most popular features.
You can check how it looks like here

If you have any other suggestions - please, open a separate issue, so we can track that faster. :)
