### ISSUE TITLE
Double optin / soft subscribe?

### ISSUE THREAD

**Issue by SteveVaneeckhout** [mailjet/mailjet-apiv3-dotnet#30]
Is there an API available to _soft_ subscribe a person to a contact list so that the subscriber will receive an email where he has to confirm the subscription?

**Comment by kmanchikov** [comment]
Hey Steve, 

The full functionality of an Double-optin process is available through Mailjet's Subscription widget. But if you would go through building that on your own through the API, there is an way and here is a good blog post which would give you the exact steps on how to achieve that. 

https://www.mailjet.com/blog/news/how-to-set-up-a-double-opt-via-mailjets-api/

**Comment by SteveVaneeckhout** [comment]
I don't like the UI of the widget and want to provide a better integration for my website using the API. If the widget can do it then the API should support it too. I'm not going to code this whole system myself as the article suggests.

**Comment by abambova** [comment]
Hi @SteveVaneeckhout ,

We are currently working on improving the UI of the widget, I do not have a specific ETA but please stay tuned. Regarding such integration, through the API the only possible way is what is already suggested by @kmanchikov . I'll close the issue but do not hesitate to open a new one if needed.
