### ISSUE TITLE
StatusCode 405

### ISSUE THREAD

**Issue by flopez2904** [mailjet/mailjet-apiv3-dotnet#34]
Hi,

I am trying to use the api but it always returns the same error.

           MailjetClient client = new MailjetClient(mailjet.clavepublica, mailjet.claveprivada)
            {
                Version = ApiVersion.V3,
            };

            MailjetRequest request = new MailjetRequest()
            {
                Resource = Listrecipient.Resource,
                ResourceId = ResourceId.Alphanumeric(id),
            }
            .Property(Listrecipient.ListName, nombre);

            MailjetResponse response = await client.PostAsync(request);

response.IsSuccessStatusCode = false
response.StatusCode = 405
{{
  "ErrorInfo": "",
  "ErrorMessage": "Method not allowed",
  "StatusCode": 405
}}

The Api keys are correct...

**Comment by abambova** [comment]
Hello @flopez2904 ,

Could you please precise the API calls you are testing? Thanks!

**Comment by abambova** [comment]
Hello @flopez2904 ,

We believe we found out the problem in the request you mentioned above, you have used post instead of get, so the correct request should be:

MailjetClient client = new MailjetClient(mailjet.clavepublica, mailjet.claveprivada)
        {
            Version = ApiVersion.V3,
        };

        MailjetRequest request = new MailjetRequest()
        {
            Resource = Listrecipient.Resource,
            ResourceId = ResourceId.Alphanumeric(id),
        }
        .Property(Listrecipient.ListName, nombre);

        MailjetResponse response = await client.GetAsync(request)

I'll close the issue, please feel free to open a new one, if needed.
