### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by spaasis** [mailjet/mailjet-apiv3-dotnet#35]
Trying out the readme examples, I get an HttpRequestException: `A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
---- System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond`

I can ping api.mailjet.com from the command prompt, but the MailJetClient doesn't get through.

I assume this this is a proxy issue. How can I configure my proxy settings with the client, or debug this otherwise? I'm running the tests on a console program.

**Comment by kmanchikov** [comment]
Hi there, 

I hope this reply finds you well. I would suggest going through a support ticket with what you are reporting above, you can open one at ( https://www.mailjet.com/feature/support/ ) with all the details included. The support guys there would be able to check your account and see if this is perhaps an connection issue or something else. 

If that doesn't help I would suggest going through a quick Traffic monitoring and checking which are the root causes of those failed connection afterwards. The tools that would be able to help you are the ones below. 

1st. Trying to capture traffic through https://mitmproxy.org/
and see what's inside the bad requests https://github.com/droe/sslsplit

Hope this would help

**Comment by goacoustic** [comment]
Hi there,
Seems like the problem with proxy server configuration. I'll close this due to inactivity.
