### ISSUE TITLE
Advised change in Send Api

### ISSUE THREAD

**Issue by mattanja** [mailjet/mailjet-apiv3-dotnet#36]
Today 2019-05-13 a change in the SendAPI v3 has been announced: As a Mailjet SendAPI v3 user, you may be impacted by a system change that will take place on June 3rd, 2019. From this date forward, the SendAPI v3 response payloads will contain an additional property: Message UUIDs, in addition to the current MessageID.

Is the Lib tested to work against the changed API? Or will a new version be provided?
Thanks!

**Comment by kmanchikov** [comment]
Hey @mattanja, 

Yes, the wrappers will handle the change, no new version will be needed. Only an additional property `MessageUUID` will be added to the response of an Send API v3 call, in addition to the already included `MessageID`.
