### ISSUE TITLE
Issue with asp.net version 4.5

### ISSUE THREAD

**Issue by jot11** [mailjet/mailjet-apiv3-dotnet#4]
.Hey guys

Hope you are doing great there !

I need to use the code of your for checking the deliver ability  of my email, 

But I am getting following error!

The type 'System.Net.Http.HttpMessageHandler' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

When I tried to create project using 4.0.0.0 version there is eror
**Install-Package : Could not install package 'Mailjet.Api 1.0.1'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with 
that framework. For more information, contact the package author.**

Please help me

**Comment by Zhivko-Mailjet** [comment]
Hi @jot11 
Thanks for reporting the issue. We will investigate and come back to you as soon as we have more information

**Comment by jot11** [comment]
The error is solved by me Itself , I have added the reference to System.Net.Http and it work 


However I am getting 401 error and error info is unauthorized , 

68110cdb522c90dcd2990cab5edf1f26

486b5119a95a25571f6d31754147b363

My username and secret key for mailjet , can u please check that

**Comment by eboisgon** [comment]
Hi @jot11 , 

thank you for coming back to us , 

I edited your comment to removed your current Mailjet credential. For security, I would advise you to reset your API credential as soon as possible by going to the following address https://app.mailjet.com/account/api_keys to avoid that they get used by someone else. 

Regarding you 401 error, could you contact us through our support with a sample of your code?

Best

**Comment by jot11** [comment]
Okay I am done with reseting it

here my code 

using System.Text;
using System.Threading.Tasks;
using Mailjet.Client;
using Mailjet.Client.Resources;
using System.Configuration;
using Newtonsoft.Json.Linq;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            RunAsync().Wait();
        }

        static async Task RunAsync()
        {
            MailjetClient client = new MailjetClient(Environment.GetEnvironmentVariable("MyUsername"), Environment.GetEnvironmentVariable("Mysecret"));
            MailjetRequest request = new MailjetRequest
            {
                Resource = Send.Resource,
            }
               .Property(Send.FromEmail, "from@solution.com")
               .Property(Send.FromName, "Mailjet Pilot")
               .Property(Send.Subject, "Your email flight plan!")
               .Property(Send.TextPart, "Dear passenger, welcome to Mailjet! May the delivery force be with you!")
               .Property(Send.HtmlPart, "<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!")
               .Property(Send.Recipients, new JArray {
                new JObject {
                 {"Email", "to@company.com"}
                 }
                });
            MailjetResponse response = await client.PostAsync(request);
            if (response.IsSuccessStatusCode)
            {
                Console.WriteLine(string.Format("Total: {0}, Count: {1}\n", response.GetTotal(), response.GetCount()));
                Console.WriteLine(response.GetData());
            }
            else
            {
                Console.WriteLine(string.Format("StatusCode: {0}\n", response.StatusCode));
                Console.WriteLine(string.Format("ErrorInfo: {0}\n", response.GetErrorInfo()));
                Console.WriteLine(string.Format("ErrorMessage: {0}\n", response.GetErrorMessage()));
                Console.ReadLine();
            }
        }
    }
}

**Comment by eboisgon** [comment]
Hi @jot11 

I suppose you are replacing "Myusername" and "Mysecret" by your API credentials  in 

`MailjetClient client = new MailjetClient(Environment.GetEnvironmentVariable("MyUsername"), Environment.GetEnvironmentVariable("Mysecret"));`

By doing simply this :

`MailjetClient client = new MailjetClient("MyUsername","Mysecret");` 

it should fix the 401 error as the Environment.GetEnvironmentVariable is looking for your API keys in the environement and probably returning some empty strings. 

Regards

Emmanuel

**Comment by jot11** [comment]
Working fine now , But  I need to know about the **status** of the message 
Ether it is deliver or not ,

**Comment by Zhivko-Mailjet** [comment]
@jot11 
For question related to the general API behavior, please reach out to our [support](https://www.mailjet.com/support/ticket). We got your question covered there.

Closing the issue as solution to the initially reported problem was provided.
