### ISSUE TITLE
Latest Nuget Assembly not signed

### ISSUE THREAD

**Issue by inicolenco** [mailjet/mailjet-apiv3-dotnet#40]
Hi it seems that the latest Nuget package assembly is not signed. This results in the following error being raised 
`Could not load file or assembly 'Mailjet.Client, Version=1.2.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)`

This is quite unfortunate as it makes the package quite unusable for enterprise solutions relying on strongly-named assemblies.

**Comment by snsrkrishna** [comment]
![image](https://user-images.githubusercontent.com/1052827/80864414-097c0480-8ca0-11ea-9d88-28fe1e111da1.png)

Team, is this assembly not yet signed. Please help us with alternative.

**Comment by esuarezlo** [comment]
All libraries which use Mailjet.Client must be no signed also. This was my solution.
