### ISSUE TITLE
Code hangs after sending email but email is sent OK (static async Task)

### ISSUE THREAD

**Issue by vikiram29** [mailjet/mailjet-apiv3-dotnet#45]
MailjetResponse response = await client.PostAsync(request).ConfigureAwait(false);
After the above line, the mail sent but code hangs. please let me know what the problem. Here is my full code
public void Button1_Click(object sender, EventArgs e)
    {
        RunAsync().Wait();

    }
    public static async Task RunAsync()
    {
        MailjetClient client = new MailjetClient("xxx","xxx")
        {
            Version = ApiVersion.V3_1,
        };
        MailjetRequest request = new MailjetRequest
        {
            Resource = Send.Resource,
        }
           .Property(Send.Messages, new JArray {
                new JObject {
                 {"From", new JObject {
                  {"Email", "xxx"},
                  {"Name", "Me"}
                  }},
                 {"To", new JArray {
                  new JObject {
                   {"Email", "xxx"},
                   {"Name", "You"}
                   }
                  }},
                 {"Subject", "My first Mailjet Email!"},
                 {"TextPart", "Greetings from Mailjet!"},
                 {"HTMLPart", "<h3>Dear passenger 1, welcome to <a href=\"https://www.mailjet.com/\">Mailjet</a>!</h3><br />May the delivery force be with you!"}
                 }
               });
        
        MailjetResponse response = await client.PostAsync(request).ConfigureAwait(false);

        if (response.IsSuccessStatusCode)
        {
            Console.WriteLine(string.Format("Total: {0}, Count: {1}\n", response.GetTotal(), response.GetCount()));
            Console.WriteLine(response.GetData());
        }
        else
        {
            Console.WriteLine(string.Format("StatusCode: {0}\n", response.StatusCode));
            Console.WriteLine(string.Format("ErrorInfo: {0}\n", response.GetErrorInfo()));
            Console.WriteLine(response.GetData());
            Console.WriteLine(string.Format("ErrorMessage: {0}\n", response.GetErrorMessage()));
        }
    }

**Comment by goacoustic** [comment]
@vikiram29 Hi, you shouldn't use blocking calls like Wait form UI thread in WinForms. Better to use Dispatcher or similar mechanics to move to the work into [the background thread](https://devblogs.microsoft.com/pfxteam/await-and-ui-and-deadlocks-oh-my/), or at least make the button click handler async:

```csharp
private async void btnSendEmail_Click(object sender, EventArgs e)
{
     await RunAsync(txtTo.Text, txtFrom.Text, txtSubject.Text, txtBody.Text);
}

**Comment by goacoustic** [comment]
I've added a comment to the readme to omit such issues.
