### ISSUE TITLE
Filter(Contact.Email, email) does not filter

### ISSUE THREAD

**Issue by fletz** [mailjet/mailjet-apiv3-dotnet#47]
I try to add a contact to a mailinglist, but for that I need it's ID. If the contact already exists, I need to get the ID via the email address. According to the documentation the following code should do this. But it doesn't it just returns 10 contacts.

```
MailjetRequest request = new MailjetRequest {
    Resource = Contact.Resource
}.Filter(Contact.Email, email);

MailjetResponse response = await client.GetAsync(request);
if (response.IsSuccessStatusCode) {
    emailUsers = response.GetData();
    Console.WriteLine(emailUsers);
}
```

Am I doing something wrong here? Or is the Filter just ignored?

**Comment by goacoustic** [comment]
Hi @fletz 

Seems like the correct way of doing so is to pass resourceId into the request itself, rather than using the filter. Obviously, this is not good that library is not providing feedback on what's wrong.
You can try this code, it does what you want:

```c#

            MailjetRequest request = new MailjetRequest
            {
                Resource = Contact.Resource,
                ResourceId = ResourceId.Alphanumeric(email)
            };

            MailjetResponse response = await client.GetAsync(request);
```

**Comment by goacoustic** [comment]
Also, I've added an explanation to the readme.
