### ISSUE TITLE
GetTotal() vs. GetCount() does not return correct values

### ISSUE THREAD

**Issue by fletz** [mailjet/mailjet-apiv3-dotnet#48]
The paging information doesn't work. If I do an unfiltered call for Contacts I get 10 results and the response tells me that the total number is 10. Which is wrong, because I have more than 10 contacts. But with the API telling me there is only 10, I can't create a solid paging.

```
MailjetRequest request = new MailjetRequest {
    Resource = Contact.Resource
};

MailjetResponse response = await client.GetAsync(request);
if (response.IsSuccessStatusCode) {
    emailUsers = response.GetData();
    Console.WriteLine("{0} - {1}", response.GetTotal(), response.GetCount());
}
```

**Comment by goacoustic** [comment]
Hi @fletz 
Seems like you need to call contacts GET with `countOnly` set to true to receive the total number of contacts for paging.
You can refer to the [API documentation](https://dev.mailjet.com/email/reference/contacts/contact/#v3_post_contact) where this is mentioned.

<details>
  <summary>Note from the API</summary>
  
_When you send a request without the countOnly query parameter, Count and Total will only return the number of extracted elements and not the overall number._
</details>

**Comment by goacoustic** [comment]
Going to close this for now.
