### ISSUE TITLE
Unable to retrieve statistics

### ISSUE THREAD

**Issue by Lucafiu** [mailjet/mailjet-apiv3-dotnet#49]
Hello,

I try to retrieve statistics, for example the stats at the APIKey level by using the example code of this page: [https://dev.mailjet.com/email/guides/getting-started/#retrieve-statistics](https://dev.mailjet.com/email/guides/getting-started/#retrieve-statistics)
```
MailjetClient client = new MailjetClient(Environment.GetEnvironmentVariable("MJ_APIKEY_PUBLIC"), Environment.GetEnvironmentVariable("MJ_APIKEY_PRIVATE"));
MailjetRequest request = new MailjetRequest
{
      Resource = Statcounters.Resource,
}
.Filter(Statcounters.CounterSource, "APIKey")
.Filter(Statcounters.CounterTiming, "Message")
.Filter(Statcounters.CounterResolution, "Lifetime");
MailjetResponse response = await client.GetAsync(request);
```

Each time I try, I get the following error : 
```
[
  {
    "ErrorInfo": "",
    "ErrorMessage": "Operation not allowed",
    "StatusCode": 401
  }
]
```

I'm really confused because I try the query on postman (which is the equivalent query to the one in C#):
https://api.mailjet.com/v3/REST/statcounters?CounterSource=APIKey&CounterTiming=Message&CounterResolution=Lifetime
and it worked perfectly.

Actually all the queries I do on the statistics using c# return the error "Operation not allowed", but when I try to do the same queries on postman, they are working.

**Comment by goacoustic** [comment]
HI @Lucafiu! 
I checked the mentioned code and seems like it works fine from C# wrapper. 
Could you please confirm that this request is still actual?

**Comment by goacoustic** [comment]
Going to close this for now. If you have more questions - please, comment on this issue or create the new one.
