### ISSUE TITLE
Is this Compatible with Azure Functions?

### ISSUE THREAD

**Issue by nhwilly** [mailjet/mailjet-apiv3-dotnet#5]
I have been trying to implement MJ in my Azure Functions app.  I tried copying the sample C# code verbatim and ran into this error:

    [6/4/2017 10:50:59 PM] Function started (Id=6f914f96-a631-48b4-be78-6b5fa96a7a12)
    [6/4/2017 10:50:59 PM] Function completed (Failure, Id=6f914f96-a631-48b4-be78-6b5fa96a7a12, Duration=35ms)
    [6/4/2017 10:50:59 PM]
    [6/4/2017 10:50:59 PM] A ScriptHost error has occurred
    [6/4/2017 10:50:59 PM] Exception while executing function: Functions.EmailProcessor. mscorlib: Exception has been thrown by the target of an invocation. TrustyFunctions: Method not found: 'Newtonsoft.Json.Linq.JArray Mailjet.Client.MailjetResponse.GetData()'.

This was failing not just for `GetData()` but for every attempt to set a property, too.

At first I thought sure it was me, so I tried several different approaches that might tell me if the problem was something in the Json I had copied.

But then I attempted to interactively execute the code in the Visual Studio 2017 Immediate Window and the same statements worked.  

I believe there is some environmental incompatibility when it comes to Azure Functions.

I like your product offering, but Azure Functions is a must-have for me.  Let me know if I can help.

**Comment by eboisgon** [comment]
Hello @nhwilly , 

Thank you for your feedback, we are going to have a look at this problem and let you know when we have a solution available.

**Comment by arnaudbreton** [comment]
Hi @nhwilly, sorry for the delay to come back to you.

After further investigations, we managed to make our sample projects running on Azure functions.
In order to troubleshoot your issue, can you provide us some sample code (please hide your API credentials) and your `project.json` file (or at least the part showing that the Mailjet dependency is properly listed)?

Thanks for your help

**Comment by nhwilly** [comment]
Sorry, I've been on the road for a few days.  Let me know if you need anything else.

Here's the entire function:

    using Mailjet.Client;
    using Mailjet.Client.Resources;
    using Microsoft.Azure.WebJobs;
    using Microsoft.Azure.WebJobs.Host;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Threading.Tasks;

    namespace Functions
    {
    public static class EmailProcessor
    {

        private static string apiKey => System.Environment.GetEnvironmentVariable("MailJetApiKey", EnvironmentVariableTarget.Process);
        private static string apiSecret => System.Environment.GetEnvironmentVariable("MailJetApiSecret", EnvironmentVariableTarget.Process);

        [FunctionName("EmailProcessor")]
        public static async Task Run([QueueTrigger("email", Connection = "AzureWebJobsStorage")]string queueEntry, TraceWriter log)
        {
            log.Info($"C# Queue trigger function processed: {queueEntry}");       
            MailjetClient client = new MailjetClient(apiKey, apiSecret);
            MailjetRequest request = new MailjetRequest
            {
                Resource = Send.Resource
            }
            .Property(Send.FromName, "Do Not Reply")
            .Property(Send.Subject, "Something happened and you should know ...")
            .Property(Send.TextPart, queueEntry)
            .Property(Send.HtmlPart, "<h1>Is This Big?</h1>")
            .Property(Send.Recipients, new JArray
            {
                new JObject
                {
                    {"Email","xxxx.xxxx@gmail.com" }
                }
            });
            MailjetResponse response = await client.PostAsync(request).ConfigureAwait(false);
            if (response.IsSuccessStatusCode)
            {
                log.Info($"Total: {response.GetTotal()} Count: {response.GetCount()}");
                log.Info(response.GetData().ToString());
            }
            else
            {
                log.Error($"Status code: {response.StatusCode}  Error: {response.GetErrorInfo()}  Error message: {response.GetErrorMessage()}");
            }

        }
    }
    }

**Comment by latanasov** [comment]
Hi @nhwilly, I am just guessing here, but could you try setting the _FromEmail_ and check if it makes any difference .
`.Property(Send.FromEmail, "someVerifiedSenderEmail@domain")`
Let me know how it goes.

**Comment by nhwilly** [comment]
OK, for starters, I can't believe I missed that line of code.  My objective was to just kick off something simple to get a feel for things.  My apologies.  Senior moment, I guess.

That said, adding the line you suggested changed nothing.  Same errors related to Json.  FWIW, I validated the sender email manually in the portal, not with API calls, if that makes any difference.

**Comment by latanasov** [comment]
Hi @nhwilly , I have tested the following code in https://functions.azure.com/try and it works fine. Maybe take a look at your project.json and bindings. Feel free to say if the code below also works for you.
**Source code:**
run.csx
```
using Mailjet.Client;
using Mailjet.Client.Resources;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Newtonsoft.Json.Linq;
using System;
using System.Threading.Tasks;
    [FunctionName("EmailProcessor")]
    public static async Task Run([QueueTrigger("email", Connection = "AzureWebJobsStorage")] string queueEntry, TraceWriter log)
    {
        log.Info($"C# Queue trigger function processed: {queueEntry}");       
        
    MailjetClient client = new MailjetClient(
        "apiKey",
        "apiSecret"
    );

        MailjetRequest request = new MailjetRequest
        {
            Resource = Send.Resource
        }
        .Property(Send.FromEmail,"verifed@mail")
        .Property(Send.FromName, "Do Not Reply")
        .Property(Send.Subject, "Something happened and you should know ...")
        .Property(Send.TextPart, "test")
        .Property(Send.HtmlPart, "<h1>Is This Big?</h1>")
        .Property(Send.Recipients, new JArray
        {
            new JObject
            {
                {"Email","xxxx.xxxx@gmail.com" }
            }
        });
        MailjetResponse response = await client.PostAsync(request).ConfigureAwait(false);
        if (response.IsSuccessStatusCode)
        {
            log.Info($"Total: {response.GetTotal()} Count: {response.GetCount()}");
            log.Info(response.GetData().ToString());
        }
        else
        {
            log.Error($"Status code: {response.StatusCode}  Error: {response.GetErrorInfo()}  Error message: {response.GetErrorMessage()}");
        }

    }
```
function.json
```
{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "function",
      "name": "queueEntry",
      "type": "httpTrigger",
      "direction": "in"
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    }
  ]
}
```
project.json

```
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "Mailjet.Api": "1.0.1"
      }
    }
   }
}
```

**Comment by nhwilly** [comment]
Ok, I got this working.

I am not using the browser based portal to write my functions.  I'm using the Azure Function Tools for Visual Studio 2017 Preview 3.  So I decided to do it your way and try it in the browser.  It worked.

But as I created the files in the portal, I noticed that the packages downloaded included NewtonSoft.Json 9.0.1.  My projects have been using 10.0.2.

I modified my version in VS 2017 and changed the Json package back to 9.0.1 and everything worked just fine.

So, looks like there's a breaking change for you guys in the latest Json update.  Thanks for following up on this and for what it's worth, the emails arrive in about 2 seconds.  That's pretty great.

**Comment by arnaudbreton** [comment]
Hey @nhwilly, glad to read we sorted this out!

We'll look into supporting NewtonSoft.Json in version 10.x. Meanwhile, we'll document better this limitation, thanks for having spotted it.

**Comment by vovikdrg** [comment]
It still not fixed....

**Comment by tsegato** [comment]
Still not working
