### ISSUE TITLE
Accepting large attachments. Parse API not performing as expected/needed

### ISSUE THREAD

**Issue by waqarii** [mailjet/mailjet-apiv3-dotnet#50]
Parse API not performing as expected/needed !
Could someone from mail jet team please share parse code with us or make it available as some sort of open source package/dll, so that we can link/integrate it with our own mail-server to receive and parse emails.
Issue needs a proper solution.
The 2 issues we currently have:
-	Size limit
-	Response from MailJet mailserver instead of a message on the webhook. Currently we cannot control the response as it goes from MailJets webservers directly to our customers, which is confusing. We need full control of the received messages.

That would solve our issue in short term and future proof once your system supports large attachments.

Thanks & Regards,
Waqar

**Comment by ngarnier** [comment]
From what you're saying about responses going to your customers instead of the webhook, there is likely an issue with your configuration. Please reach out to support from your account directly as they'll be better suited to help.

Closing as it's not an issue with the wrapper.
