### ISSUE TITLE
how do I form a web request without this API?

### ISSUE THREAD

**Issue by laurentopia** [mailjet/mailjet-apiv3-dotnet#52]
This API is far too verbose and complicated for simple tasks like adding contact.
I'd like to do something where you form the webrequest by hand adding a header for the APIKey, akin to mailchimp's:
`	var request = new UnityWebRequest(url, UnityWebRequest.kHttpVerbPOST);
		request.SetRequestHeader("Content-Type", "application/json");
		request.SetRequestHeader("Authorization", "apikey " + _apiKey);
		var json = string.Format(mailchimpJsonFormat, email);
		var jsonBytes = Encoding.UTF8.GetBytes(json);
		request.uploadHandler = new UploadHandlerRaw(jsonBytes);
		request.downloadHandler = new DownloadHandlerBuffer();
		yield return request.SendWebRequest();`

**Comment by goacoustic** [comment]
Hi @laurentopia,

This SDK is created to make the developer's life easier to reduce the amount of boilerplate code.
It's definitely possible to use MailJet API without this SDK through any HTTP C# implementation like WebRequest/HttpClient/RestSharp/UnityWebRequest etc.

Please, refer to our [REST documentation](https://dev.mailjet.com/email/guides/) to do so.
