### ISSUE TITLE
Sandbox mode is not available in Send API 3.1

### ISSUE THREAD

**Issue by manojbiswanath** [mailjet/mailjet-apiv3-dotnet#54]
Good afternoon,

I cannot use the "Sandbox" mode in Send API 3.1 in C# .Net. I am using Mailjet.Api 1.2.2 version (.NET wrapper  -> https://github.com/mailjet/mailjet-apiv3-dotnet) and I have also searched in all other versions and still cannot find Sandbox attribute in the library.

According to this documentation it should be available.
https://dev.mailjet.com/email/guides/send-api-v31/#sandbox-mode

Here we can see the Sendbox attribute is missing in the Send class:
https://github.com/mailjet/mailjet-apiv3-dotnet/blob/master/Mailjet.Client/Resources/Send.cs

Please let me know how can I use it or if its not available now, then when can we expect this feature to be released, as I need to test the API calls for mass emails in bulk without actually delivering the emails.
(Please also refer to my attached screenshots.)

Thank you very much !
![Screenshot (195)](https://user-images.githubusercontent.com/41157506/92227638-d55f5d00-eea6-11ea-8bda-8daa96c51ff6.png)

**Comment by wassim-azirar** [comment]
Hello @manojbiswanath 

I just created a class like this to solve the problem, instead of waiting the library to be updated

```c#
public static class Send
{
	public static readonly ResourceInfo Resource = new ResourceInfo("send", null, ResourceType.Send);

	public const string Recipients = "Recipients";
	public const string To = "To";
	public const string Cc = "cc";
	public const string Messages = "Messages";
        public const string SandboxMode = "SandboxMode";
	public const string AdvanceErrorHandling = "AdvanceErrorHandling";
	// other const you may need
}
```

**Comment by manojbiswanath** [comment]
Hi @wassim-azirar 

Thanks a lot. Its working now !
