### ISSUE TITLE
Strongly typed models

### ISSUE THREAD

**Issue by enkelmedia** [mailjet/mailjet-apiv3-dotnet#55]
While i understand that using JArray and JObject might be a simple way to go I would vote for strongly typed models for stuff that could be done with the API

**Comment by goacoustic** [comment]
hi @enkelmedia, thank you for raising this issue.

I've added a possibility to use strongly typed models for sending transactional emails, as this is one of the most popular features.
You can check how it looks like [here](https://github.com/mailjet/mailjet-apiv3-dotnet/blob/e150ab97c067a426478bb4a2c18c757b1c4cb52b/Mailjet.Tests/Integration/SendTransactionalEmailIntegrationTests.cs#L40)

If you need other methods - please, open a new issue for each method, this way we can prioritize the features and add them faster :)
