### ISSUE TITLE
NuGet.org package doesn't seem to be up-to-date

### ISSUE THREAD

**Issue by BuriedStPatrick** [mailjet/mailjet-apiv3-dotnet#58]
I was scratching my head as to why my code wouldn't compile on `Mailjet.Client.Resources.Send.SandboxMode`. After a quick decompile, seems that the property is indeed missing. Highly unusual since that exact issue is supposedly [fixed in the v1.2.2 tag diff](https://github.com/mailjet/mailjet-apiv3-dotnet/compare/v1.2.2...master).

**Comment by BuriedStPatrick** [comment]
I misinterpreted which branch was ahead. In any case, would be nice with a patched 1.2.3 version that addresses the issue.

**Comment by goacoustic** [comment]
@BuriedStPatrick HI!
Will check regarding the release of the new version.

**Comment by BuriedStPatrick** [comment]
@goacoustic Thanks! I temporarily fixed it for myself by manually adding the SandboxMode-property. But it would very much be appreciated if this package could get some of love, I've had a few issues with it that have led me to resorting to cloning the project down manually rather than just using the nuget-package. :)

**Comment by BuriedStPatrick** [comment]
I re-opened this and renamed, as I think it's important that the NuGet-package is updated.
