### ISSUE TITLE
Add contact via api does not start trigger automation

### ISSUE THREAD

**Issue by vfiorentino** [mailjet/mailjet-apiv3-dotnet#6]
I'm adding my contacts to the mailjet list via api and it's working properly, but this list is linked to an automation workflow and the trigger that is set to "When a contact is added to a list" is not being started.

I tested by adding the contact through the mailjet website and the contact entered correctly in the automation workflow.

Is it possible for the automation workflow to be started also when the contact is added via api?

**Comment by latanasov** [comment]
Hi @vfiorentino, this question is not wrapper related. Please contact Mailjet support for general API questions.

**Comment by Vetm** [comment]
This problem is still not fixed.
