### ISSUE TITLE
How to use complex variables with the TransactionalEmailBuilder

### ISSUE THREAD

**Issue by ChiefWiggum** [mailjet/mailjet-apiv3-dotnet#64]
How can I add complex variables (e.g. a list of products) to an email with the `TransactionalEmailBuilder`? Somehow the `WithVariable() `allows only to add a string, not an object. Is there a reason for this behaviour?

**Comment by goacoustic** [comment]
Hi @ChiefWiggum, thanks for contributing!

I'm gonna check your PR later today, want to ensure some scenarios.

**Comment by ChiefWiggum** [comment]
Ok, thanks. After my PR I discovered a `Clone` Method on the `TransactionalEmailBuilder` which will probably not create proper clones of the variables. So that's an issue I haven't figured out/thought of a solution yet...

**Comment by goacoustic** [comment]
@ChiefWiggum regarding Clone method - yep, but as for me, that's correct behavior - it performs a deep clone of the builder properties, but uses shallow copies of passed parameters.

BTW I've released a new version with your changes, which should be available through NuGet.
