### ISSUE TITLE
V3.1 Api

### ISSUE THREAD

**Issue by yornstei** [mailjet/mailjet-apiv3-dotnet#67]
I'm having issues using the V3.1 Api from C#

Console App
netcoreapp3.1
`<PackageReference Include="Mailjet.Api" Version="2.0.1" />`

Sample code
```csharp
using System;
using System.Threading.Tasks;
using Mailjet.Client;
using Mailjet.Client.Resources;
using Mailjet.Client.TransactionalEmails;

namespace MailJetIssueConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            RunAsync().Wait();
        }

        static async Task RunAsync()
        {
            MailjetClient _client = new MailjetClient("MJ_APIKEY_PUBLIC", "MJ_APIKEY_PRIVATE")
            {
                Version = ApiVersion.V3_1
            };;

            MailjetRequest request = new MailjetRequest
            {
                Resource = Send.Resource,
            };

            // construct your email with builder
            var email = new TransactionalEmailBuilder()
                .WithFrom(new SendContact("from@test.com"))
                .WithSubject("Test subject")
                .WithHtmlPart("<h1>Header</h1>")
                .WithTo(new SendContact("to@test.com"))
                .Build();

            // invoke API to send email
            var response = await _client.SendTransactionalEmailAsync(email);

            Console.WriteLine(response.Messages);
        }
    }
}
```

Compile Error: Cannot find symbol 'Version' . 

The sample code for using V3.1 came from c# example [here](https://dev.mailjet.com/email/guides/send-api-v31/)

I couldn't find 'Version' in the MailjetClient.cs in the repo either [line](https://github.com/mailjet/mailjet-apiv3-dotnet/blob/master/Mailjet.Client/MailjetClient.cs)

Was it removed? is it part of a different version?

**Comment by goacoustic** [comment]
@yornstei Hi!

You don't need to specify the specific API version in v2+ - the client will handle that under the hood.
I'm gonna find out how to update docs.

The right code that uses API v3.1 should be something like 

```c#
            MailjetClient _client = new MailjetClient("MJ_APIKEY_PUBLIC", "MJ_APIKEY_PRIVATE");

            // construct your email with builder
            var email = new TransactionalEmailBuilder()
                .WithFrom(new SendContact("from@test.com"))
                .WithSubject("Test subject")
                .WithHtmlPart("<h1>Header</h1>")
                .WithTo(new SendContact("to@test.com"))
                .Build();

            // invoke API to send email
            var response = await _client.SendTransactionalEmailAsync(email);

```

**Comment by yornstei** [comment]
Hi @goacoustic. Thanks for the reply.

Are you sure the client default to v3.1? The following :

```csharp
MailjetRequest request = new MailjetRequest
{
    Resource = Send.Resource,
};
Console.WriteLine(request.BuildUrl());
```

Logs - `v3/send`

**Comment by goacoustic** [comment]
@yornstei more precisely, it takes an API version from the resource itself.

Send uses v3 for backward compatibility, and this will use V3.1 (But I'd still use transactional email builder instead, as it removes the necessity to construct JObjects manually). 

```C#
            MailjetRequest request = new MailjetRequest
            {
                Resource = SendV31.Resource,
            };
```

Maybe, you have some specific reason to use it through the resource approach?

**Comment by yornstei** [comment]
@goacoustic oh, thanks; I didn't realize there's a SendV31 option. 

I'm not using the transactional builder as i cannot find how to set the sandbox option.

**Comment by goacoustic** [comment]
It should be easy enough :)

```c#
await _client.SendTransactionalEmailAsync(email, isSandboxMode: true);
```

**Comment by yornstei** [comment]
Works great. Thanks for you're help.
