### ISSUE TITLE
Problem with getting template after account move

### ISSUE THREAD

**Issue by sven5** [mailjet/mailjet-apiv3-dotnet#68]
Hi support team,

my account has been moved from Azure to a local Mailjet account. 
Currently, the following request does not return a template:

`https://api.mailjet.com/v3/REST/template/1723793/detailcontent`

Error 404 - but the template does exist and it worked in the past.

I'm unable to file a support request, the support website is only blank and full of js errors.
I don't know my account password, so I cannot logout and sign-in again. Strange.

**Comment by goacoustic** [comment]
Hi @sven5,

There's a possibility that one of the browser extensions is blocking js on the support site.
Could you try to open a ticket [here](https://www.mailjet.com/contact/) from the anonymous window? This page allows to do so even without login.

Also, you can try to reset your password via [this](https://app.mailjet.com/auth/forgot_password) link.

**Comment by sven5** [comment]
Hi @goacoustic 

Thank you, I was able to reset my password. 
I opened a ticket about the problem with the detailcontent.

Regards
Sven
