### ISSUE TITLE
Send API v3.1 Constants

### ISSUE THREAD

**Issue by froitag** [mailjet/mailjet-apiv3-dotnet#7]
Any chance to get v3.1 compatible `Send` constants any time soon? E.g. in a `Send3_1` static class?

Or even better of course a real poco model? ;)

**Comment by latanasov** [comment]
Hi @froitag , thank you for your request- we do have similar propositions for the other wrappers and we will certainly add it to our list of future improvements. I cannot for the moment give you any ETA (will be sooner than later :) ), but I'll keep you posted.

**Comment by Thoradin89** [comment]
Hello @froitag 

We've taken your suggestion into consideration. Indeed we're planning future improvements and we'll communicate them via the standard channels once ready. This issue will be closed.

Regards,
T.
