### ISSUE TITLE
ApiV3 requires sender details when sender is specified on template

### ISSUE THREAD

**Issue by VagueGit** [mailjet/mailjet-apiv3-dotnet#70]
We send emails using Mailjet Transactional Templates in production with `Mailjet.Api Version=1.2.2`. Transactional templates must specify sender details as part of the template definition.

In testing the upgrade to `Mailjet.Api Version 2.0.1` emails sent using transactional templates return
```
"StatusCode": 400,
"ErrorInfo": "At least FromEmail or Sender must be provided"
```
This appears to be a breaking change that violates the DRY principle. The sender is set in the template. It should not be necessary to set the sender in the request.

**Comment by gilly42** [comment]
Got same Problem whenn updating from 1.x.x to 2.0.1

**Comment by longhornleads** [comment]
Also have the same problem but downgrading to 1.x.x does not fix this so is there another workaround?

**Comment by longhornleads** [comment]
Okay so the workaround is to make the call yourself for now (at least for me). I personally am using RestSharp and it works fine. So the problem is with this code and not MailJet.

**Comment by VagueGit** [comment]
We work around it like this
```
MailjetRequest mailjetRequest = new MailjetRequest
{
    Resource = TemplateDetailcontent.Resource,
    ResourceId = ResourceId.Numeric(templateId)
};
MailjetResponse response = await mailjetClient.GetAsync(mailjetRequest);
JArray data = response.GetData();
JToken headers = data.FirstOrDefault()["Headers"];
emailTemplate.SenderEmail = $"{headers.SelectToken(nameof(EmailTemplate.SenderEmail))}";
emailTemplate.SenderName = $"{headers.SelectToken(nameof(EmailTemplate.SenderName))}";
emailTemplate.Subject = $"{headers.SelectToken(nameof(EmailTemplate.Subject))}";

```
This gets the sender email sender name and the subject from the template. They are then used to send the email.

**Comment by goacoustic** [comment]
@longhornleads  @VagueGit @gilly42 
Hi guys, 
Thanks for raising this!

I'm trying to understand what is the root cause - is it this C# library, API validation or issue with specific template? 
I've created a new transactional email template and I'm able to send it w/o setting the sender:

```c#
            var email = new TransactionalEmailBuilder()
                .WithTo(new SendContact("edited@edited.com"))
                .WithTemplateId(2906084)
                .Build();

            var response = await _client.SendTransactionalEmailAsync(email);
```

Could you please provide more info, so we can look at it further?

**Comment by VagueGit** [comment]
As I indicated in the original post, the API returns 
```
"StatusCode": 400,
"ErrorInfo": "At least FromEmail or Sender must be provided"
```
so I guess that makes it an API validation issue

However we do not use `TransactionalEmailBuilder`. We send transactional email like this
```
mailjetRequest
    .Property(Send.MjTemplateID, templateId)
```

**Comment by nieve** [comment]
Same issue here, we've been using your nuget like so :  
```csharp
            request.Property(Send.Messages, new JArray {
                new JObject {
                    {"From", new JObject {
                        {"Email", "our@email.address"},
                        {"Name", "our name"}
                    }},
                    {"To", new JArray {
                        new JObject {
                            {"Email", user.Email},
                            {"Name", user.FullName}
                        }
                    }},
                    {"TemplateID", TemplateId},
                    {"Variables", new JObject
                    {
                        { "name", user.FullName }
                    }},
                    {"TemplateLanguage", true}
                }
            });
            var response = await _client.PostAsync(request);
```

I'd appreciate a response from the jet mail people, seeing that we had to go back to using 1.2.2

**Comment by goacoustic** [comment]
@nieve Hi! Just to clarify - you were using v1.2.2 and it's working with the same code you provided, but when you update the nuget package to the latest, it starts returning a bad request. Am I getting it right?

**Comment by nieve** [comment]
@goacoustic that is correct, the code I provided earlier on is working with 1.2.2 and stopped working once we have upgraded to 2.0.2
The error we received after upgrading is the same as the one @VagueGit referred to at the beginning of this issue.

**Comment by goacoustic** [comment]
@nieve @VagueGit seems like I've got the problem
there is 2 versions of API - V3 and V31
From the code you provided, request looks like for API v3. In v1.2.2 you set this parameter in the client itself, when creating an instance of MailjetClient. 
In the latest versions, client determines API version from the resource. Send.Resource is for API v3, and SendV31.Resource for API v3.1.

So we can use SendV31.Resource like this

```c#
            var request = new MailjetRequest()
            {
                Resource = SendV31.Resource,
            };
```

to make an old code working after updating.

**Comment by nieve** [comment]
@goacoustic thanks for getting back to us. I'm a bit tied up with other issues currently, but promise to give this solution a try and get back here to let you and the others know if that actually solved my issue.

**Comment by laurentAstonIf** [comment]
Hi 

Current version 1.2.2, trying to convert to 2.0.2

It looks like that depending on Send.Resource or SendV31.Resource 
we can use or not the string defined as const in Send
Ex : with Send.Resource i can use Send.HtmlPart which is "Html-Part"
and if i'm amending the Resource to us SendV31 i have a validation error : At least a htmlpart, textpart,.. must be provided
=> to make it works i have to remove Send.Htmlpart and used "htmlpart" instead

=> if the const have changed their value can you define them in SendV31 ?

ps : it might be a good idea to enable sourcelink in your nuget

**Comment by VagueGit** [comment]
Apologies for the delay getting back on this. We had to wait until our customers were on holiday before deploying this.

We are now able to use `Mailjet.Api.2.0.2` combining suggestions from @goacoustic and @nieve. Note below that in order to use variables it is necessary to set `.WithTemplateLanguage(true)`

```
mailjetRequest.Resource = SendV31.Resource;
TransactionalEmail transactionalEmail = new TransactionalEmailBuilder()
    .WithTo(new SendContact(emailAddress))
    .WithTemplateId(templateId)
    .WithTemplateLanguage(true)
    .WithVariables(templateVariables)
    .Build();

TransactionalEmailResponse response = await mailjetClient.SendTransactionalEmailAsync(transactionalEmail);
if (response.Messages.Length == 1)
    break;

```

**Comment by mjamilmoughal** [comment]
Hi, By writing **FromEmail** instead of **From** fixed the issue for me.
```
                            {
                                "FromEmail", 
                                new JObject {
                                    {"Email", "test@test.com"},
                                    {"Name", "no-name@test.com"}
                            }
```
