### ISSUE TITLE
SendTransactionalEmailAsync is not exposed in the IMailjetClient interface

### ISSUE THREAD

**Issue by peterlindholm** [mailjet/mailjet-apiv3-dotnet#72]
Is there a specific reason for the SendTransactionalEmailAsync method not be publicly available on the IMailjetClient interface?

**Comment by goacoustic** [comment]
@peterlindholm nice catch!

This method is implemented as an extension method to not mix with existing methods in this interface (they are kinda different by nature). 
Nevertheless, it makes sense to extend an interface instead of implementation.
