### ISSUE TITLE
Promote MailJetClient Extenisons to Interface

### ISSUE THREAD

**Issue by rgarrison12345** [mailjet/mailjet-apiv3-dotnet#79]
I am attempting to do unit testing with the sendtransactionalemailAsync methods on IMailJetClient using the Moq library. I am trying to setup the mock object on IMailJetClient. However this fails because these methods are extension methods on IMailJetClient interface. I think it wouldn't be too much of a change by taking the methods on those extensions, and defining them in the interface. Then implementing them on MailJetClient concrete class. Maybe for those who have written their own class that implements on IMailJetClient,

**Comment by maffelbaffel** [comment]
Same problem. We currently work around this issue by wrapping the class in another interface provided by us.

**Comment by rgarrison12345** [comment]
@maffelbaffel I created a PR to address this issue https://github.com/mailjet/mailjet-apiv3-dotnet/pull/81 hopefully it will be taken into consideration
