### ISSUE TITLE
Nuget Packages for 4.6 and 4.6.1

### ISSUE THREAD

**Issue by mixerp** [mailjet/mailjet-apiv3-dotnet#8]
Could you please update packages for

- .NETFramework 4.6
- .NETFramework 4.6.1?

**Comment by latanasov** [comment]
Hi @mixerp , thank you for your request, we will soon evaluate it and come back to you. 
Regards,
Lyubomir

**Comment by Thoradin89** [comment]
Hello @ghost,

All packages were updated.

Regards,
Todor

**Comment by huismansander** [comment]
When using MailjetClient (v1.2.2) in my project (.net framework 4.6.1) I'll get the following runtime error: Could not load file or assembly System.Net.Http, Version = 4.0.0.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a or one of its dependencies. The system cannot find the specified file.

What is causing this error and how can I solve (or work around) it?
