### ISSUE TITLE
GetTemplate limit offset return count and total same value

### ISSUE THREAD

**Issue by ddo88** [mailjet/mailjet-apiv3-dotnet#84]
I'm using de client with filters limit and offset but in all cases return the same value on count an total, this is a weird behaviour, why replicate the same value this api? even the documentation says that is the same value, but for correct pagination should show the total of templates, no?

![imagen](https://user-images.githubusercontent.com/885227/132261783-8fdaa9dc-63cc-43ce-a713-dbffd67d28c0.png)

![imagen](https://user-images.githubusercontent.com/885227/132261763-59b6c719-6752-40ca-bd82-d9b2bade248d.png)

![imagen](https://user-images.githubusercontent.com/885227/132261855-8c419b8c-a55f-493c-80a6-5e4d54f375da.png)

**Comment by dmytrosvystun88** [comment]
![image](https://github.com/mailjet/mailjet-apiv3-dotnet/assets/4784289/dad9bbf1-b000-42a2-a36d-07ef486f40fa)

**Comment by dmytrosvystun88** [comment]
This has been already fixed. Closing the issue.

**Comment by ddo88** [comment]
thanks!!
