### ISSUE TITLE
SendTransactionalEmailAsync returns TransactionalEmailResponse where Messages = null

### ISSUE THREAD

**Issue by mewid** [mailjet/mailjet-apiv3-dotnet#85]
When using **SendTransactionalEmailAsync**, the .net sdk sometimes returns a **TransactionalEmailResponse** where the **Messages** array are null.

By looking at the code it seems like the issue is:

SendTransactionalEmailAsync demands that the MailjetResponse.Content conforms to the structure of TransactionalEmailResponse:
`TransactionalEmailResponse result = clientResponse.Content.ToObject<TransactionalEmailResponse>();`

However this does not always seem to be the case; _MailjetClients_ PostAsync-method uses a method GetContent to decide this structure before executing the code I mentioned above, and some errors will generate a json structure that is not an array of messages. This means that when we are using SendTransactionalEmailAsync , some errors will return a TransactionalEmailResponse where Messages are just set to null. It fails on our side, and all information of the actual error has been lost so its hard know really what happened.

**Comment by george-stylianou** [comment]
Any updates regarding this?

**Comment by icottiero** [comment]
I've encountered the same issue where Messages is `null` in the response. I see that the issue was resolved, but the latest package version on NuGet is from before the fix. When do you plan to release the new package?
