### ISSUE TITLE
I am looking for a bouncestatistics call example

### ISSUE THREAD

**Issue by MichaelKappel** [mailjet/mailjet-apiv3-dotnet#88]
Can you point me in the direction of a C# bouncestatistics example call?

**Comment by MichaelKappel** [comment]
I created a repository that was able to pull bouncestatistics I mat me able to get permission from my employer to contribute it back to this repo if you would like, otherwise you can close this request

**Comment by dmytrosvystun88** [comment]
Here is a link to an example of bouncestatistics call: https://dev.mailjet.com/email/reference/message-events/#v3_get_bouncestatistics.
