### ISSUE TITLE
Implement dashboard statistics inside my asp.net website  

### ISSUE THREAD

**Issue by jot11** [mailjet/mailjet-apiv3-dotnet#9]
Hi I have got the reference of this thread , I want to implement  to check that how many emails are sent , not sent or bounced . Do you have any example code to do the same or  it will be fine if you can guide me for the same. 

Thanks

**Comment by latanasov** [comment]
Hi @jot11,
You'd probably want to access the[ /messagestatistics](https://dev.mailjet.com/email-api/v3/messagestatistics/)  resource. We have a C# [example ](https://dev.mailjet.com/guides/?csharp#messages)in our guide. Let me now if this answers your question.

Regards,
Lyubomir

**Comment by jot11** [comment]
hi @latanasov  

Thanks for you references, that is for each message and I have to store message id in my database
to check the message or I am wrong here ?
I have got another reference https://dev.mailjet.com/guides/?csharp#api-key-totals that is helping me to get the total messages sent using my api .
It works kool , Is there any way to get these api totals for any time interval , I mean datewise .

**Comment by latanasov** [comment]
Hi @jot11 `GET on /messagesentstatistics/$ID` is for a single message while GET on  `/messagesentstatistics` is for multiple messages. Please take a look at the the API[ Reference](https://dev.mailjet.com/email-api/v3/messagesentstatistics/) . If you have further questions please raise a ticket through Mailjet Support.
