### ISSUE TITLE
Timeout issue ? "Unable to send email using Mailjet"

### ISSUE THREAD

**Issue by GuillaumeSpera** [mailjet/mailjet-apiv3-dotnet#93]
Hello there,
We are using the Mailjet API (and this package) for an automated process and yesterday (for the first time after a year of using the same tool), we ended up with multiple error messages spread in a 10 hour range.

Here is the message :

> Unable to send email using Mailjet. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (api.mailjet.com:443))

Would you be aware of the reason for that ?
Is there a way to increase the timeout configuration if there is one ?

This is how we use the MailjetClient
```
    var client = new MailjetClient(config.Mail.ApiKey, config.Mail.ApiSecret);
    var request = new MailjetRequest
    {
        Resource = MailjetResources.SendV31.Resource
    }
    .Property(MailjetResources.Send.Messages, new JArray { messageObject });

    logger.LogDebug($"[Mailjet] Sending email to {recipientCount} recipients entitled \"{mailMessage.Subject}\".");

    var response = await client.PostAsync(request);
    if (response == null)
        throw new Exception("no response from mailjet");

    if (!response.IsSuccessStatusCode)
        throw new Exception(response.GetErrorMessage());

    logger.LogDebug("[Mailjet] Email Sent.");
}
```
The error is thrown by `if (!response.IsSuccessStatusCode)`.

Thanks

**Comment by goacoustic** [comment]
Hi @GuillaumeSpera,

seems like a transient network error that can happen due to various reasons, usually bound to a cloud provider or a network path from your ISP to it.

The usual way to cope with that kind of error - implementing retry logic to try again faulty requests. 
Ofc there is a way to set a custom connection timeout by passing the customly configured HTTP client:

```
var httpClient = new HttpClient();
httpClient.Timeout = TimeSpan.FromSeconds(60);
var mailjetClient = new MailjetClient(httpClient);
```

but usually, retry logic is a better alternative.

**Comment by guillaume-spera-shift** [comment]
@goacoustic thank you for the answer.
I agree that the retry logic is better in this case.
My issue is that the emails were sent by mailjet even though the timeout occurred. That's why I al worried about applying retry logic and spamming the recipients of the emails.
