### ISSUE TITLE
Release v2.1.0 is a breaking change and does not expose transactional emails on interface

### ISSUE THREAD

**Issue by JSkimming** [mailjet/mailjet-apiv3-dotnet#95]
The latest v2.1.0 has broken our automated build system by moving the extension methods [MailjetClientExtensions](https://github.com/mailjet/mailjet-apiv3-dotnet/blob/v2.0.2/Mailjet.Client/TransactionalEmails/MailjetClientExtensions.cs) to the [MailjetClient](https://github.com/mailjet/mailjet-apiv3-dotnet/blob/3b129b/Mailjet.Client/MailjetClient.cs#L165-L173) implementation.

This has broken our build because we code against the [IMailjetClient](https://github.com/mailjet/mailjet-apiv3-dotnet/blob/v2.0.2/Mailjet.Client/IMailjetClient.cs) interface, and you have not added the new methods to the interface.

Furthermore, since you have removed methods from the public API, namely [MailjetClientExtensions](https://github.com/mailjet/mailjet-apiv3-dotnet/blob/v2.0.2/Mailjet.Client/TransactionalEmails/MailjetClientExtensions.cs), this warrants a major version update, assuming you are following [semantic versioning](https://semver.org/).

**Comment by JSkimming** [comment]
I've raised PR #96 to add the methods to the `IMailjetClient` interface. Overall the changes warrant a major version bump because it is still a breaking change.

**Comment by goacoustic** [comment]
@JSkimming thanks for noting and PR!
That was an unintended change.

About version bump - I agree, in projects, there will be unresolved using references, which will require a code change.
