### ISSUE TITLE
mailjet client does not contain a definition for version

### ISSUE THREAD

**Issue by mohamedalijinnah** [mailjet/mailjet-apiv3-dotnet#98]
as per the [documentation ](http://dev.mailjet.com/guides/?csharp)I have installed mailjet.api latest version3 .0  But im getting this error 

'MailjetClient' does not contain a definition for 'Version'

Am i missing something?

![image](https://user-images.githubusercontent.com/43814278/181017472-6f3c53ad-e71f-40e9-9517-aa226a926287.png)

**Comment by goacoustic** [comment]
Hi @mohamedalijinnah ,

Thanks for the question.
now we dont need to specify API version, it will be detected automatically. For example:

```
// this call will use API v3
MailjetRequest request = new MailjetRequest
         {
            Resource = Send.Resource
         };

// this call will use API v3.1
MailjetRequest request = new MailjetRequest
         {
            Resource = Send31.Resource
         };

```

**Comment by mohamedalijinnah** [comment]
Thanks @goacoustic  for the response. 

It worked with SendV31.Resource. 

![image](https://user-images.githubusercontent.com/43814278/181240428-2701598c-2c96-42b6-b217-ca03b2054e4a.png)
